/**
 * Compiles data/lexicon/*.json + data/names.json + data/suffixes.json into the
 * compact artifacts bundled inside the khudam package at build time. No
 * runtime fetch, ever.
 * Output (gitignored): packages/converter/src/generated/{lexicon,suffixes}.ts
 * Run with: bun run build:data
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import {
  NAMES_FILE,
  REPO_ROOT,
  SUFFIXES_FILE,
  compareWords,
  loadLexicon,
  readEntriesFile,
  readSuffixesFile,
  type Source,
} from "./lib.ts";

const OUT_DIR = join(REPO_ROOT, "packages", "converter", "src", "generated");
const OUT_FILE = join(OUT_DIR, "lexicon.ts");
const SUFFIX_OUT_FILE = join(OUT_DIR, "suffixes.ts");

/** Compact candidate: [traditional, latin, sense, verified, source-code]. */
type CompactCandidate = [string, string, string, 0 | 1, string];

const SOURCE_CODES: Record<Source, string> = {
  "wmk-import": "w",
  wiktionary: "k",
  manual: "m",
  community: "c",
};

const merged = loadLexicon();
if (existsSync(NAMES_FILE)) {
  for (const entry of readEntriesFile(NAMES_FILE)) {
    const existing = merged.get(entry.cyrillic);
    if (!existing) {
      merged.set(entry.cyrillic, entry);
      continue;
    }
    for (const cand of entry.candidates) {
      if (!existing.candidates.some((c) => c.traditional === cand.traditional)) {
        existing.candidates.push(cand);
      }
    }
  }
}

const table: Record<string, CompactCandidate[]> = {};
for (const key of [...merged.keys()].sort(compareWords)) {
  table[key] = merged.get(key)!.candidates.map((c) => [
    c.traditional,
    c.latin ?? "",
    c.sense ?? "",
    c.verified ? 1 : 0,
    SOURCE_CODES[c.source] ?? "c",
  ]);
}

const json = JSON.stringify(table);
const banner =
  "// AUTO-GENERATED by scripts/build-data.ts — do not edit, do not commit.\n" +
  "// Compiled from data/lexicon/*.json and data/names.json.\n" +
  "// Format: JSON string of { [cyrillic]: Array<[traditional, latin, sense, verified 0|1, source w|k|m|c]> }\n" +
  "// (kept as a string: JSON.parse of a big literal loads faster than a huge object literal.)\n";
const ts =
  banner +
  `export const LEXICON_JSON: string = ${JSON.stringify(json)};\n` +
  `export const LEXICON_ENTRY_COUNT = ${merged.size};\n`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_FILE, ts, "utf8");
console.log(
  `Compiled ${merged.size} entries -> ${relative(REPO_ROOT, OUT_FILE).replaceAll("\\", "/")} ` +
    `(${(Buffer.byteLength(ts, "utf8") / 1024 / 1024).toFixed(2)} MB)`,
);

/** Compact suffix row: [cyrillic, traditional, latin, sense, attach, gender, verified, joined]. */
type CompactSuffix = [string, string, string, string, string, string, 0 | 1, 0 | 1];

const suffixRows: CompactSuffix[] = (existsSync(SUFFIXES_FILE) ? readSuffixesFile(SUFFIXES_FILE) : []).map((s) => [
  s.cyrillic,
  s.traditional,
  s.latin ?? "",
  s.sense,
  s.attach ?? "",
  s.gender ?? "",
  s.verified ? 1 : 0,
  s.joined ? 1 : 0,
]);
const suffixBanner =
  "// AUTO-GENERATED by scripts/build-data.ts — do not edit, do not commit.\n" +
  "// Compiled from data/suffixes.json (rules: data/GRAMMAR.md).\n" +
  "// Format: JSON string of Array<[cyrillic, traditional, latin, sense, attach, gender, verified 0|1]>\n";
const suffixTs =
  suffixBanner +
  `export const SUFFIXES_JSON: string = ${JSON.stringify(JSON.stringify(suffixRows))};\n` +
  `export const SUFFIX_COUNT = ${suffixRows.length};\n`;
writeFileSync(SUFFIX_OUT_FILE, suffixTs, "utf8");
console.log(
  `Compiled ${suffixRows.length} suffix rows -> ${relative(REPO_ROOT, SUFFIX_OUT_FILE).replaceAll("\\", "/")}`,
);
